# A Quick Tour of TensorFlow

__Quick-Summary (Why Tensorflow):__

1. Similar to numpy but with GPU-Support
2. Distributed Computing
3. Just-in-Time Compiler (JIT)
4. Models can be exported as Graph
5. Autodiff

## Categorizatiopn of TensorFlow API
__Notes:__
1. There are fundamentally low- and high-level APIs
2. Code will be compiled to C++. 
3. Some operations have multiple implementations (CPU/GPU)  
    3.1 Those Operations are called _Kernels_

<img src="../../img/1201.png" width=700 height=700/>


## Tensors and Operations

Tensor: 

- Seem that a Tensor needs a rectangular shape. That means the nested arrays need to have the same length!   
    - e.g.: ```tf.constant([[1,2,3], [4,5,6]])``` is ok; ```tf.constant([[1,2,3], [4,5])``` is _not_ ok!
- Does not perform automatic type conversion!
    - e.g.: You can not add int-tensor with float-tensor without typecasting first!
    

In [3]:
import tensorflow as tf
import pandas as pd
import numpy as np

### Constans and Variables

- Variables change over time (e.g. Weights in net -> Backpropagation)

In [23]:
tf.constant([[1,2,3], [4,5,6]]) # function

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [24]:
tf.Variable([[1,2,3], [4,5,6]]) # class

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

### Type Conversion

In [16]:
a = tf.constant([[1,2], [1,2]]) # int tensor
b = tf.constant([[1,2], [1,.5]]) # float tensor

#### Type Casting - ```tf.cast()```

In [19]:
b = tf.cast(b, tf.int32)

In [20]:
a+b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [2, 2]])>

### Tensors and Numpy

-  Numpy functions can be used on tensors and vice versa

__Important Note__: 
- Keras also implements some low-level functions. Use them if you want to save/deploy Keras Model

```
from tensorflow import keras

K = keras.backend
K.square(tensor)

```

In [25]:
np.square(a)

array([[1, 4],
       [1, 4]], dtype=int32)

In [27]:
tf.square(np.array([[1,2], [1,2]]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 4],
       [1, 4]])>

## Other Data Structures

1. __Sparse Tensor (tf.SparseTensor)__
    - Tensor containing mostly 0
2. __Tensor Arrays (tf.TensorArray)__  
    - List of Tensors
    - Fixed sized by default (can be changed)
    - All tensor inside MUST have the same __shape__ and __dtype__
3. __Ragged tensors (tf.RaggedTensor)__
    - Static nested list of tensors
    - Fixed size, shape and dtype
4. __String Tensor (tf.string)__
    - Are regulat Tensor (variable or constant) with dtype=string
    - tf.string is atomic --> No length in tensor shape!
    - Automatically encoded to UTF-8
5. __Sets__
    - Normals Sets
6. __Queues__
    - Store tensors across multiple steps
    -  TensorFLow has multiple Ques

In [33]:
tf.Variable(["!npfvoew"])

<tf.Variable 'Variable:0' shape=(1,) dtype=string, numpy=array([b'!npfvoew'], dtype=object)>